export class CreateFuncionariosDto {
    nome_servidor:string;
    nome_mae:string;
    rg:string;
    cpf:string;
    rs:number;
    status:string;
    cns:string;
    data_nascimento:Date;
    idade:number;
    genero:string;
    municipio_residencia:string;
    logradouro:string;
    numero:number;
    bairro:string;
    telefone:string;
    email:string;
    cargo_servidor:string;
    createdAt:Date;
    updatedAt:Date;
}