import { Document } from "mongoose";

export interface Presos extends Document{
    det_nome: string;
    det_nomesocial:string;
    det_matricula:number;
    det_digito:number;
    matricula_digito: string;
    det_execucao:string;
    det_execucao_tipo:string;
    det_pai: string;
    det_mae:string;
    det_datanascimento:Date;
    idade:number;
    inclusao_tipo:string;
    inclusao_tipo_cor_fundo:number;
    inclusao_tipo_cor_fonte:number;
    inclusao_tipo_transito_comum:string;
    inclusao_tipo_transito_provisor:string;
    inclusao_tipo_transferencia:string;
    inclusao_tipo_automatica:string;
    inc_codigo: number;
    inc_inclusaotipo_id:number
    inc_datainclusao:Date;
    inc_procedencia:string;
    inc_raio: number;
    inc_cela:number;
    localizacao:string;
    rg:number;
    cpf:string;
    ra_aluno:string
    cartao_sus:string;
    titulo_eleitoral:string;
    titulo_eleitoral_situacao:string;
    det_certmilitar_reservista:string;
    nacionalidade:string;
    det_profissao:string;
    escolaridade:string;
    termo:string;
    residencia_cidade:string;
    procedencia_cidade:string;
    inc_dataprisao:Date;
    inc_artigo:string;
    inc_bo:string;
    autoridade: string;
    autoridade_cidade:string;
    inc_processo: string;
    inc_vara:string;
    inc_comarca:string;
    exc_codigo:number;
    exc_exclusaotipo_id: number;
    exclusao_tipo:string;
    exclusao_tipo_cor_fonte: string;
    exclusao_tipo_transito_provisor:string;
    exclusao_tipo_transferencia:string;
    exclusao_tipo_liberdade:string;
    exc_dataexclusao: Date;
    exc_destino:string;
    exclusao_cidade:string;
    imposta_ano: number;
    imposta_mes: number;
    imposta_dia: number;
    local_atual:string;
    regime_id:string;
    reginme: string;
    regime_cor: number;
    det_condenado: string;
    data_deferido_sa: string;
    det_sit_processual: string;
    transito: string;
    seguro: string;
    disciplinar: string;
    conduta: string;
    inc_pedido_vaga: string;
    inc_pedido_data: Date;
    inc_pedido_destino_id: number;
    pedido_destino: string;
    inc_pedido_obs:string;
    det_pront_cimic: string;
    det_pront_cimic_origem: string;
    det_filhos: string;
    etinia:string;
    status:string;
    createdAt: Date;
    updatedAt: Date;
}